services:
  # Servicio Web Unificado de Producción (Node.js API + React Vite UI + Prisma)
  - type: web
    name: luxlunch
    runtime: docker
    plan: free
    dockerContext: .wasp/out
    dockerfilePath: .wasp/out/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: WASP_WEB_CLIENT_URL
        sync: false
